<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV6GHmis\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV6GHmis/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV6GHmis.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV6GHmis\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV6GHmis\App_KernelDevDebugContainer([
    'container.build_hash' => 'V6GHmis',
    'container.build_id' => '529c3832',
    'container.build_time' => 1652527957,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV6GHmis');
